### ISSUE TITLE
Failed on launch

### ISSUE THREAD

**Issue by Symbian9** [sk1project/color-picker#2]
### System info

- **Version:** `1.0rc1_20191227`
- **OS:** Debian 9.x (amd64)

### Expected behavior

Launch as expected.

### Actual behavior

Failed on launch.

### Terminal log

```
$ color-picker
Traceback (most recent call last):
  File "/usr/bin/color-picker", line 22, in <module>
    cp2.run()
  File "/usr/lib/color-picker-1.0rc1/cp2/__init__.py", line 68, in run
    from .app import ColorPickerApp
  File "/usr/lib/color-picker-1.0rc1/cp2/app.py", line 23, in <module>
    import wal
  File "/usr/lib/color-picker-1.0rc1/wal/__init__.py", line 18, in <module>
    from .base import Application, PaletteWindow, EntryPopover
  File "/usr/lib/color-picker-1.0rc1/wal/base.py", line 36
    menu_str = f'<?xml version="1.0" encoding="UTF-8"?>' \
                                                       ^
SyntaxError: invalid syntax
```

**Comment by maxim-s-barabash** [comment]
Required Python 3.6

**Comment by sk1project** [comment]
@Symbian9 the problem source is fixed. Please try latest package and report result.

**Comment by Symbian9** [comment]
> Please try latest package and report result.

When fixed rebuild packages would be available?

- https://downloads.sk1project.net/color-picker/nightbuilds/Debian/

**Comment by sk1project** [comment]
@Symbian9 they are already there.
